version: '3.7'
services:

  app:
    build:
      context: ./docker/php
    container_name: app
    volumes:
      - ./app/:/home/source/main
    working_dir: /home/source/main

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=b2b
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    build:
      context: ./docker/nginx
    container_name: web-nginx
    ports:
      - "8000:80"
    depends_on:
      - app
      - mysql
    volumes: 
      - ./app/:/home/source/main

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  default:
    driver: bridge
    name: app-network